<a href="https://colab.research.google.com/github/Andre270203/Aprendiendo_TensorFlow/blob/main/tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
# pip install tensorflow

In [3]:
import tensorflow as tf

# Ejemplo de como crear diferentes tensores

Un tensor es una estructura matemática que se utiliza para representar datos multidimensionales. En términos sencillos, un tensor es como una matriz, pero con más de dos dimensiones.

Los tensores son esenciales en TensorFlow porque permiten representar y manipular datos multidimensionales, lo que es fundamental para la construcción y entrenamiento de modelos de aprendizaje automático.

In [5]:
string = tf.Variable("this is a string", tf.string)
number = tf.Variable(123, tf.int16)
floating = tf.Variable(3.456,tf.float64)

# RANK

El rank de un tensor se refiere al número de dimensiones o ejes que tiene un tensor.

Por ejemplo, un tensor escalar (un número) tiene rank 0, un tensor vectorial (como un vector columna o fila) tiene rank 1, un tensor matriz tiene rank 2 y un tensor tridimensional (como un cubo de datos) tiene rank 3.

In [7]:
rank1_tensor = tf.Variable(["test",'ok','tim'], tf.string)
rank2_tensor = tf.Variable([["test",'ok'],["andre", "yes"]],tf.string)

# Check the rank

El método .rank se utiliza para obtener el rank o la cantidad de dimensiones de un tensor. El rank de un tensor es importante para comprender cómo se puede operar con él y para determinar la forma correcta de una operación en TensorFlow.

In [8]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

# Check the shape

El método .shape se utiliza para obtener la forma o tamaño de un tensor. La forma de un tensor es una tupla que contiene la cantidad de elementos en cada dimensión del tensor.

Es muy útil en TensorFlow porque permite conocer la forma de los datos que se están manejando en una red neuronal, lo que ayuda a diseñar la arquitectura de la red y a entender cómo se están realizando las operaciones en cada capa.

In [9]:
rank2_tensor.shape

TensorShape([2, 2])

#Changing shape

El método .reshape se utiliza para cambiar la forma de un tensor sin cambiar sus elementos. El método .reshape devuelve un nuevo tensor con la misma cantidad de elementos que el tensor original, pero con una forma diferente.

Es útil en TensorFlow porque permite cambiar la forma de los datos que se están manejando en una red neuronal, lo que puede ser necesario en algunas situaciones. Por ejemplo, cuando se está trabajando con imágenes, es común cambiar la forma de los tensores para que se ajusten a la entrada de una capa de convolución.

In [18]:
tensor1 = tf.ones([1,2,3]) #tf.ones() creates a shape [1,2,3] tensor full of ones
tensor2 = tf.reshape(tensor1, [2,3,1]) #reshape existing data to shape [2,3,1]
tensor3 = tf.reshape(tensor2, [3,-1]) #-1 tells the tensor to calculate the size of the dimenson in that place
                                      #this will reshape the tensor to [3,2]

In [17]:
print(tensor1)
print("--------------------------")
print(tensor2)
print("--------------------------")
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
--------------------------
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
--------------------------
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


# Types of sensor


1.   Variable
2.   Constant
3.   Placeholder
4.   SparseTensor






# Evaluate tensor

Evaluar un tensor significa obtener su valor numérico. En otras palabras, cuando se evalúa un tensor, se calcula el valor numérico de todos los elementos del tensor.

# Ejemplo de reshape

In [ ]:
t= tf.zeros([5,5,5,5])
print(t)

In [ ]:
t = tf.reshape(t,[125,-1])
print(t)